version: "3.8"

services:
  # Backend service
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - mynet
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://alexander:admin1234@postgres:5432/sge_2

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    restart: on-failure
    networks:
      - mynet

  # Postgres service
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=sge_2
      - POSTGRES_USER=alexander
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5455:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
